import fs from "fs";
import path from "path";

const VAULT_PATH = process.env.ZEUS_VAULT_PATH || "G:\\ZEUS-VAULT";

const CAPABILITIES = [
  {
    name: "Hestia Search",
    file: "Hestia Search.md",
    summary: "Retrieval básico sobre ficheiros markdown do Vault.",
    links: ["Hestia", "Retrieval Layer", "ZEUS Runtime"]
  },
  {
    name: "Hestia Context Builder",
    file: "Hestia Context Builder.md",
    summary: "Monta contexto operacional a partir de resultados de retrieval.",
    links: ["Hestia", "Retrieval Layer", "ZEUS Runtime", "Provider Layer"]
  },
  {
    name: "Hestia Brief",
    file: "Hestia Brief.md",
    summary: "Comprime resultados de retrieval em blocos operacionais utilizáveis.",
    links: ["Hestia", "Hestia Context Builder", "Retrieval Layer"]
  },
  {
    name: "Hestia Sections",
    file: "Hestia Sections.md",
    summary: "Recupera secções completas em vez de linhas isoladas.",
    links: ["Hestia", "Hestia Brief", "Retrieval Layer"]
  },
  {
    name: "Hestia Entity Graph",
    file: "Hestia Entity Graph.md",
    summary: "Extrai relações entre entidades através de wikilinks e referências.",
    links: ["Hestia", "Olympus", "Runtime Governance", "Retrieval Layer"]
  },
  {
    name: "Hestia Memory Write",
    file: "Hestia Memory Write.md",
    summary: "Cria capturas de memória persistente dentro do Vault.",
    links: ["Hestia", "Obsidian Vault", "ZEUS Runtime"]
  },
  {
    name: "ZEUS Handoff",
    file: "ZEUS Handoff.md",
    summary: "Gera handoffs de sessão com estado operacional, queue e próximos passos.",
    links: ["Hestia", "ZEUS Runtime", "Runtime Governance", "SAFE_OVERNIGHT_MODE"]
  },
  {
    name: "ZEUS Auto Runner",
    file: "ZEUS Auto Runner.md",
    summary: "Executa tarefas da queue com validação e geração de reports.",
    links: ["ZEUS Runtime", "Execution Policy", "Runtime Governance", "Themis"]
  },
  {
    name: "ZEUS Policy Gate",
    file: "ZEUS Policy Gate.md",
    summary: "Bloqueia comandos inseguros antes da execução automática.",
    links: ["Themis", "Execution Policy", "Runtime Governance", "ZEUS Auto Runner"]
  },
  {
    name: "ZEUS Task Planner",
    file: "ZEUS Task Planner.md",
    summary: "Analisa sinais runtime e propõe prioridades operacionais.",
    links: ["Athena", "ZEUS Runtime", "Hestia", "Runtime Governance"]
  },
  {
    name: "ZEUS Task Generator",
    file: "ZEUS Task Generator.md",
    summary: "Transforma sinais runtime em tasks pendentes na queue.",
    links: ["Athena", "ZEUS Task Planner", "ZEUS Auto Runner", "Execution Policy"]
  },
  {
    name: "ZEUS Queue Status",
    file: "ZEUS Queue Status.md",
    summary: "Mostra estado das tasks: pending, running, completed e failed.",
    links: ["ZEUS Auto Runner", "Runtime Governance", "Hestia"]
  },
  {
    name: "Vault Normalizer",
    file: "Vault Normalizer.md",
    summary: "Detecta artefactos, nomes malformados e ruído no Vault.",
    links: ["Hestia", "Obsidian Vault", "Runtime Governance", "Themis"]
  },
  {
    name: "SAFE_OVERNIGHT_MODE Runtime",
    file: "SAFE_OVERNIGHT_MODE Runtime.md",
    summary: "Executa manutenção segura e limitada durante períodos sem supervisão.",
    links: ["SAFE_OVERNIGHT_MODE", "Themis", "Hestia", "ZEUS Runtime"]
  }
];

function now(): string {
  return new Date().toISOString();
}

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeCapability(cap: any) {
  const dir = path.join(VAULT_PATH, "20-architecture", "runtime-capabilities");
  ensureDir(dir);

  const filePath = path.join(dir, cap.file);

  const content = `---
type: runtime-capability
status: active
created: ${now()}
tags:
  - zeus
  - runtime
  - hestia
  - capability
---

# ${cap.name}

## Operational Summary

${cap.summary}

## Runtime Role

This capability is part of the ZEUS local-first operational cognitive runtime.

## Related

${cap.links.map((l: string) => `- [[${l}]]`).join("\n")}

## Current Status

Active v0 capability.

## Notes

Generated by ZEUS Vault Graph Materializer.
`;

  fs.writeFileSync(filePath, content, "utf8");
  return filePath;
}

function writeIndex(files: string[]) {
  const indexPath = path.join(VAULT_PATH, "20-architecture", "ZEUS Runtime Capabilities.md");

  const content = `---
type: runtime-index
status: active
created: ${now()}
tags:
  - zeus
  - runtime
  - index
---

# ZEUS Runtime Capabilities

## Operational Summary

This note indexes the active ZEUS runtime capabilities currently implemented.

## Capabilities

${CAPABILITIES.map(c => `- [[${c.name}]]`).join("\n")}

## Core Links

- [[ZEUS Runtime]]
- [[Hestia]]
- [[Olympus]]
- [[Runtime Governance]]
- [[Execution Policy]]
- [[SAFE_OVERNIGHT_MODE]]
- [[Themis]]
- [[Athena]]
- [[Hephaestus]]

## Generated Files

${files.map(f => `- ${f}`).join("\n")}
`;

  fs.writeFileSync(indexPath, content, "utf8");
  return indexPath;
}

function main() {
  const written: string[] = [];

  for (const cap of CAPABILITIES) {
    written.push(writeCapability(cap));
  }

  const index = writeIndex(written);

  console.log("ZEUS VAULT GRAPH MATERIALIZER");
  console.log(`Vault: ${VAULT_PATH}`);
  console.log(`Capability notes written: ${written.length}`);
  console.log(`Index: ${index}`);

  for (const f of written) {
    console.log(`- ${f}`);
  }
}

main();
